### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

### ISSUE THREAD

**Issue by ghost** [CodeXTF2/PyHmmm#1]
python handler.py

Traceback (most recent call last):
  File "/home/xor7/PyHmmm/handler.py", line 3, in <module>
    from havoc.service import HavocService
  File "/home/xor7/PyHmmm/havoc/service.py", line 21, in <module>
    class HavocService:
  File "/home/xor7/PyHmmm/havoc/service.py", line 23, in HavocService
    Socket: websocket.WebSocketApp = None
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

**Comment by CodeXTF2** [comment]
works for me. can you try replacing the havoc-py library prepackaged with a new copy from https://github.com/HavocFramework/havoc-py and let me know if it fixes anything, this looks like a havoc-py issue not an issue with my agent/handler.

**Comment by ghost** [comment]
Turns out that i have installed the wrong pip module 'websocket', while the correct one was 'websocket-client'
https://stackoverflow.com/a/48731964

**Comment by CodeXTF2** [comment]
lol

**Comment by ghost** [comment]
pip moment

**Comment by CodeXTF2** [comment]
indeed

**Comment by emanuelecys4** [comment]
you can solve this issue in this way
```
pip uninstall websocket-client
pip uninstall websocket
pip install websocket-client
```
