### ISSUE TITLE
Handshake status 400 Bad Request

### ISSUE THREAD

**Issue by alijnclarke** [CodeXTF2/PyHmmm#5]
Just trying this out on the latest Havoc build, getting the following error, previously worked fine, so assuming it's a breaking change on Havoc's end.

`[*] Connect to Havoc service api
[-] Websocket error: Handshake status 400 Bad Request
`

**Comment by CodeXTF2** [comment]
weird il look at it when i get time

**Comment by alijnclarke** [comment]
Seems to work ok in the dev branch, would imagine it'll be fixed on the next release
